CREATE TABLE IF NOT EXISTS blueprints(
    id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL UNIQUE,
    status ENUM('DRAFT', 'PUBLISHED') NOT NULL,
    secured BOOLEAN DEFAULT false,
    fields JSON,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
